name: Doxygen Action

on:
  push:
    branches:
      - main
      - asm_branch
      - corewar_branch
  pull_request:
    branches:
      - main
      - asm_branch
      - corewar_branch
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.4.0
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./docs/dconfig" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
